routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PruebaTestController;
use App\Http\Controllers\ClientesController;
use App\Http\Controllers\PedidosTable;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\MesasController;
use App\Http\Controllers\EstadodoController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource("horariosprueba" , PruebaTestController::class);
Route::resource("cliente" , ClientesController::class);
Route::resource("Pedido" , PedidosTable::class);
Route::resource("menutable" , MenuController::class);
Route::resource("mesastable" , MesasController::class);
Route::resource("estadotable" , EstadodoController::class);

resources/views/WMesa/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div align="center">
            <h2>Agregar Nuevo Horario</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('mesastable.index') }}"> Regresar</a>
        </div>

        <form action="{{ route('mesastable.store') }}" method="POST">
            @csrf

            <div class="row">
                <div>
                    <div class="form-group">
                        <strong>Numero de mesa:</strong>
                        <input type="varchar" name="numero_mesa" class="form-control"
                            placeholder="Ingrese el numero de mesa">
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Color de mesa:</strong>
                        <input type="varchar" name="color_mesa" class="form-control"
                            placeholder="Ingrese el color de la mesa deseada">
                    </div>
                </div>


                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/WMesa/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar la Mesa</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('mesastable.index') }}"> Regresar</a>
            </div>
        </div>
    </div>
    <form action="{{ route('mesastable.update',$mesastable->id) }}" method="POST">
        @csrf
        @method('PUT')
         <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Ingresar el Numero de Mesa:</strong>
                    <input type="varchar" name="numero_mesa" class="form-control" value="{{ $mesastable->numero_mesa }}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Ingresar el color de Mesa:</strong>
                    <input type="varchar" name="color_mesa" class="form-control" value="{{ $mesastable->color_mesa }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </form>
@endsection

resources/views/WMesa/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <br />
        <h1 align="center">REPORTE DE HORARIOS DE ATENCIÓN</h1>
        <div>
            <a class="btn btn-success" href="{{ route('mesastable.create') }}">Crear</a>
        </div>
        <br />
        @if (Session::get('success'))
            <div class="alert alert-success">
                <p>{{ Session::get('success') }}</p>
            </div>
        @endif
        <table class="table">
            <tr>
                <th>Id</th>
                <th>Numero de mesa</th>
                <th>Color de mesa</th>
                <th>Acciones</th>
            </tr>
            @foreach ($mesastable as $mesa)
                <tr>
                    <td>{{ $mesa->id}}</td>
                    <td>{{ $mesa->numero_mesa }}</td>
                    <td>{{ $mesa->color_mesa }}</td>
                    <td><a class="btn btn-primary" href="{{ route('mesastable.edit',$mesa) }}">
                        <i class="fa-solid fa-pen-to-square"></i>
                    </a>
                    <form action="{{ route('mesastable.destroy',$mesa->id) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-primary"><i class="fas fa-trash-alt"></i></button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
</div>
@endsection