routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PruebaTestController;
use App\Http\Controllers\ClientesController;
use App\Http\Controllers\PedidosTable;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\MesasController;
use App\Http\Controllers\EstadodoController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource("horariosprueba" , PruebaTestController::class);
Route::resource("cliente" , ClientesController::class);
Route::resource("Pedido" , PedidosTable::class);
Route::resource("menutable" , MenuController::class);
Route::resource("mesastable" , MesasController::class);
Route::resource("estadotable" , EstadodoController::class);

app/Models/Estado.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Estado extends Model
{
    use HasFactory;
    protected $table = "estado_mesa";
    protected $primarykey = "id ";
    public $timestamps = false;
    protected $fillable = [
        "id",
        "numero_mesa ",
        "estado_ocupada",
    ];
}

resources/views/Estados/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div align="center">
            <h2>Agregar estado de mesa</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('estadotable.index') }}"> Regresar</a>
        </div>

        <form action="{{ route('estadotable.store') }}" method="POST">
            @csrf

            <div class="row">
                <div>
                    <div class="form-group">
                        <strong>Numero de mesa:</strong>
                        <input type="float" name="numero_mesa" class="form-control"
                            placeholder="Ingresar el numero de mesa">
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Estado de mesa:</strong>
                        <input type="varchar" name="estado_ocupada" class="form-control"
                            placeholder="Ingrese el estado de la mesa">
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/Estados/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar Estado de la Mesa</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('estadotable.index') }}"> Regresar</a>
            </div>
        </div>
    </div>
    <form action="{{ route('estadotable.update',$estadotable->id) }}" method="POST">
        @csrf
        @method('PUT')
         <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Numero de la Mesa:</strong>
                    <input type="text" name="numero_mesa" class="form-control" value="{{ $estadotable->numero_mesa }}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Estado de la Mesa:</strong>
                    <input type="varchar" name="estado_ocupada" class="form-control" value="{{ $estadotable->estado_ocupada }}">
                </div>
            </div>
           
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </form>
@endsection

resources/views/Estados/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <br />
        <h1 align="center">REPORTE DE ESTADOS DE MESAS</h1>
        <div>
            <a class="btn btn-success" href="{{ route('estadotable.create') }}">Crear</a>
        </div>
        <br />
        @if (Session::get('success'))
            <div class="alert alert-success">
                <p>{{ Session::get('success') }}</p>
            </div>
        @endif
        <table class="table">
            <tr>
                <th>Id</th>
                <th>Numero de mesa</th>
                <th>Estado de la mesa</th>
                <th>Acciones</th>
            </tr>
            @foreach ($estadotable as $estado)
                <tr>
                    <td>{{ $estado->id  }}</td>
                    <td>{{ $estado->numero_mesa }}</td>
                    <td>{{ $estado->estado_ocupada }}</td>
                    <td><a class="btn btn-primary" href="{{ route('estadotable.edit',$estado) }}">
                        <i class="fa-solid fa-pen-to-square"></i>
                    </a>
                    butoon
                    <form action="{{ route('estadotable.destroy',$estado->id) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-primary"><i class="fas fa-trash-alt"></i></button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
</div>
@endsection