routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PruebaTestController;
use App\Http\Controllers\ClientesController;
use App\Http\Controllers\PedidosTable;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\MesasController;
use App\Http\Controllers\EstadodoController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource("horariosprueba" , PruebaTestController::class);
Route::resource("cliente" , ClientesController::class);
Route::resource("Pedido" , PedidosTable::class);
Route::resource("menutable" , MenuController::class);
Route::resource("mesastable" , MesasController::class);
Route::resource("estadotable" , EstadodoController::class);

resources/views/ClienteW/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div align="center">
            <h2>Agregar Nuevo Cliente</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('cliente.index') }}"> Regresar</a>
        </div>

        <form action="{{ route('cliente.store') }}" method="POST">
            @csrf

            <div class="row">
                <div>
                    <div class="form-group">
                        <strong>Nombre del Cliente:</strong>
                        <input type="varchar" name="nombre_cliente" class="form-control"
                            placeholder="Ingrese el nombre del cliente">
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Telefono del Cliente:</strong>
                        <input type="varchar" name="telefono_cliente" class="form-control"
                            placeholder="Ingrese el telefo del cliente">
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Direccion del Cliente:</strong>
                        <input type="varchar" name="direccion_cliente" class="form-control"
                            placeholder="Ingrese la direccion del cliente">
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Ciudad del Cliente:</strong>
                        <input type="varchar" name="ciudad_cliente" class="form-control"
                            placeholder="Ingrese la ciudadl del cliente">
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/ClienteW/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar datos del Cliente</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('cliente.index') }}"> Regresar</a>
            </div>
        </div>
    </div>
    <form action="{{ route('cliente.update',$cliente->id) }}" method="POST">
        @csrf
        @method('PUT')
         <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Nombre del Cliente:</strong>
                    <input type="varchar" name="nombre_cliente" class="form-control" value="{{ $cliente->dia_Atencion }}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Telefono del Cliente:</strong>
                    <input type="varchar" name="telefono_cliente" class="form-control" value="{{ $cliente->hora_apertura }}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Direccion del Cliente:</strong>
                    <input type="varchar" name="direccion_cliente" class="form-control" value="{{ $cliente->hora_cierre }}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Ciudad del Cliente:</strong>
                    <input type="varchar" name="ciudad_cliente" class="form-control" value="{{ $cliente->hora_cierre }}">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </form>
@endsection

resources/views/ClienteW/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <br />
        <h1 align="center">REPORTE DE CLIENTES</h1>
        <div>
            <a class="btn btn-success" href="{{ route('cliente.create') }}">Crear</a>
        </div>
        <br />
        @if (Session::get('success'))
            <div class="alert alert-success">
                <p>{{ Session::get('success') }}</p>
            </div>
        @endif
        <table class="table">
            <tr>
                <th>Id</th>
                <th>Nombre del Cliente</th>
                <th>Telefono del Cliente</th>
                <th>Direccion del Cliente </th>
                <th>Ciudad del cliente</th>
                <th>Acciones</th>
            </tr>
            @foreach ($cliente as $horario)
                <tr>
                    <td>{{ $horario->id  }}</td>
                    <td>{{ $horario->nombre_cliente }}</td>
                    <td>{{ $horario->telefono_cliente }}</td>
                    <td>{{ $horario->direccion_cliente }}</td>
                    <td>{{ $horario->ciudad_cliente }}</td>
                    <td><a class="btn btn-primary" href="{{ route('cliente.edit',$horario) }}">
                        <i class="fa-solid fa-pen-to-square"></i>
                    </a>
                    <form action="{{ route('cliente.destroy',$horario->id) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-primary"><i class="fas fa-trash-alt"></i></button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
</div>
@endsection