routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PruebaTestController;
use App\Http\Controllers\ClientesController;
use App\Http\Controllers\PedidosTable;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\MesasController;
use App\Http\Controllers\EstadodoController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource("horariosprueba" , PruebaTestController::class);
Route::resource("cliente" , ClientesController::class);
Route::resource("Pedido" , PedidosTable::class);
Route::resource("menutable" , MenuController::class);
Route::resource("mesastable" , MesasController::class);
Route::resource("estadotable" , EstadodoController::class);

resources/views/TestHorarios/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div align="center">
            <h2>Agregar Nuevo Horario</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('horariosprueba.index') }}"> Regresar</a>
        </div>

        <form action="{{ route('horariosprueba.store') }}" method="POST">
            @csrf

            <div class="row">
                <div>
                    <div class="form-group">
                        <strong>Día de Reserva:</strong>
                        <input type="date" name="dia_Atencion" class="form-control"
                            placeholder="Ingrese el día de reserva">
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Hora Inicio de Reserva:</strong>
                        <input type="time" name="hora_apertura" class="form-control"
                            placeholder="Ingrese la hora de la reserva">
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Hora Fin de Reserva:</strong>
                        <input type="time" name="hora_cierre" class="form-control"
                            placeholder="Ingrese la hora fin reserva">
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/TestHorarios/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar Horario de Atención</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('horariosprueba.index') }}"> Regresar</a>
            </div>
        </div>
    </div>
    <form action="{{ route('horariosprueba.update',$horariosprueba->id) }}" method="POST">
        @csrf
        @method('PUT')
         <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Día Atención:</strong>
                    <input type="date" name="dia_Atencion" class="form-control" value="{{ $horariosprueba->dia_Atencion }}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Hora Inicio Atención:</strong>
                    <input type="time" name="hora_apertura" class="form-control" value="{{ $horariosprueba->hora_apertura }}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Hora Fin Atención:</strong>
                    <input type="time" name="hora_cierre" class="form-control" value="{{ $horariosprueba->hora_cierre }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </form>
@endsection

resources/views/TestHorarios/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <br />
        <h1 align="center">REPORTE DE HORARIOS DE RESERVAS</h1>
        <div>
            <a class="btn btn-success" href="{{ route('horariosprueba.create') }}">Crear</a>
        </div>
        <br />
        @if (Session::get('success'))
            <div class="alert alert-success">
                <p>{{ Session::get('success') }}</p>
            </div>
        @endif
        <table class="table">
            <tr>
                <th>Id</th>
                <th>Dia Atención</th>
                <th>Hora De Apertura</th>
                <th>Hora De Cierre</th>
                <th>Botones</th>
            </tr>
            @foreach ($horariosprueba as $horario)
                <tr>
                    <td>{{ $horario->id }}</td>
                    <td>{{ $horario->dia_Atencion }}</td>
                    <td>{{ $horario->hora_apertura }}</td>
                    <td>{{ $horario->hora_cierre }}</td>

                    <td><a class="btn btn-primary" href="{{ route('horariosprueba.edit',$horario) }}">
                        <i class="fa-solid fa-pen-to-square"></i>
                    </a>
                    <form action="{{ route('horariosprueba.destroy',$horario->id) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-primary"><i class="fas fa-trash-alt"></i></button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
</div>
@endsection